services:
  external-server:
    image: external-server
    entrypoint: ["python3", "/home/bringauto/external_server/main.py", "-c", "/home/bringauto/config/for_docker.json", "-i", "mosquitto"]
    restart: always
    networks:
      - bring-emulator

networks:
  bring-emulator:
    name: bring-emulator
